// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6JY2mI4CuHEjEJMYdFCVOPNvh3a2QpE',
    appId: '1:171878797779:web:179c7d8fba60e50a429f26',
    messagingSenderId: '171878797779',
    projectId: 'aluhub-2026',
    authDomain: 'aluhub-2026.firebaseapp.com',
    storageBucket: 'aluhub-2026.firebasestorage.app',
    measurementId: 'G-3WDDDJT9R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRBP1rmdhHZnFUBjmKQilDhafmFueB_U',
    appId: '1:171878797779:android:1b5c7cd113deaa7e429f26',
    messagingSenderId: '171878797779',
    projectId: 'aluhub-2026',
    storageBucket: 'aluhub-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLeURoXlObvjGb8ZFUWNX5prOvyD50ks',
    appId: '1:171878797779:ios:110ad2314283e307429f26',
    messagingSenderId: '171878797779',
    projectId: 'aluhub-2026',
    storageBucket: 'aluhub-2026.firebasestorage.app',
    iosBundleId: 'com.alu.campusLaunchpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLeURoXlObvjGb8ZFUWNX5prOvyD50ks',
    appId: '1:171878797779:ios:110ad2314283e307429f26',
    messagingSenderId: '171878797779',
    projectId: 'aluhub-2026',
    storageBucket: 'aluhub-2026.firebasestorage.app',
    iosBundleId: 'com.alu.campusLaunchpad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK6JY2mI4CuHEjEJMYdFCVOPNvh3a2QpE',
    appId: '1:171878797779:web:6f0c8cef7437345e429f26',
    messagingSenderId: '171878797779',
    projectId: 'aluhub-2026',
    authDomain: 'aluhub-2026.firebaseapp.com',
    storageBucket: 'aluhub-2026.firebasestorage.app',
    measurementId: 'G-F4Q1CN03GS',
  );
}
